### ISSUE TITLE
my_imports中的anim_effects不存在

### ISSUE THREAD

**Issue by yaoshenwang** [cigar666/my_manim_projects#2]
您好，my_imports.py中有from my_manim_projects.my_utils.anim_effects import *，但my_utils中没有该文件。
运行中NameError: name 'FadeOutRandom' is not defined 的错误不知道是不是来源于此。

**Comment by cigar666** [comment]
谢谢提醒。anim_effects.py之前未上传，现已上传，添加到对应位置应该就没问题了
